deploy/lighting demo/unpackaged/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Steps_Completed__c</fullName>
        <label>Steps Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SyscDeviceDataBatch.cls
public with sharing class SyscDeviceDataBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Patient_Id__c, Full_Name__c, Gender__c, Steps_Completed__c, Goal__c, Height__c FROM Patient__c ORDER BY createdDate ASC');
    }
    
	public void execute(Database.BatchableContext BC, List<Patient__c> patientList) {
        
		String todaysDate =String.valueOf(System.today());
        todaysDate = todaysDate.replace(' 00:00:00', '');
        List<Patient__c> patientListToUpdate = new List<Patient__c>();
        for(Patient__c patient :patientList){
            Integer stepsCompleted = 0;
            String url = FitForceUtility.ACTIVITY_API.replace('TODAY', todaysDate);
            String activityJson = FitForceUtility.doHTTPCallout(FitForceUtility.GET, url);
            ActivityWrapper activityWrapper = (ActivityWrapper) JSON.deserialize(activityJson, Type.forName('ActivityWrapper'));
            for(ActivityWrapper.Activities act :activityWrapper.activities){
                System.debug('Steps :'+act.steps);
                if(act.steps != NULL){
                    patient.Steps_Completed__c = Integer.valueOf(act.steps);
                    patientListToUpdate.add(patient);
                }
            }
        }
        Database.update(patientListToUpdate);
	}
    
	public void finish(Database.BatchableContext BC) {    
	}
}